language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - pear install --alldeps pear/PHP_CodeSniffer
  - pear install --alldeps phpunit/PHP_Invoker
  - pear install --alldeps phpunit/DbUnit
  - pear install --alldeps phpunit/PHPUnit_Selenium
  - pear install --alldeps phpunit/PHPUnit_Story
  - phpenv rehash

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
