language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
  - npm install -g grunt-cli harp bower cordova
  - npm install -g testem phantomjs casperjs

install:
  - npm install
  - bower install

notifications:
  email:
    recipients:
      - alert@worker.com
    on_success: change
    on_failure: always
