---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8

inputs:
- name: source-code

run:
  path: sh
  args:
  - -c
  - |
    set -eoux pipefail
    cd ./source-code
    npm install -g nsp
    nsp check
