---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: blazemeter/taurus
    tag: latest

inputs:
- name: ci

run:
  path: sh
  args:
  - -c
  - |
    set -eux
    cd ./ci
    export TERM=dumb
    bzt ./concourse-ci/pipelines/bzt-tests/config-aggregator.yml
