---
jobs:
- name: test-unboxit-sequelgen
  plan:
  - get: ci
    trigger: true
  - get: source-code
    resource: unboxit-sequelgen
    trigger: true
  - task: audit-test
    file: ci/concourse-ci/tasks/audit-test/task.yml
  - task: nsp-test
    file: ci/concourse-ci/tasks/nsp-test/task.yml
  - task: snyk-test
    file: ci/concourse-ci/tasks/snyk-test/task.yml
    params:
      SNYK_TOKEN: {{snyk-token}}
      SNYK_USER_ID: {{snyk-user-id}}

- name: test-unboxit-nosequelgen
  plan:
  - get: ci
    trigger: true
  - get: source-code
    resource: unboxit-nosequelgen
    trigger: true
  - task: audit-test
    file: ci/concourse-ci/tasks/audit-test/task.yml
  - task: nsp-test
    file: ci/concourse-ci/tasks/nsp-test/task.yml
  - task: snyk-test
    file: ci/concourse-ci/tasks/snyk-test/task.yml
    params:
      SNYK_TOKEN: {{snyk-token}}
      SNYK_USER_ID: {{snyk-user-id}}

- name: test-unboxit-elming
  plan:
  - get: ci
    trigger: true
  - get: source-code
    resource: unboxit-elming
    trigger: true
  - task: audit-test
    file: ci/concourse-ci/tasks/audit-test/task.yml
  - task: nsp-test
    file: ci/concourse-ci/tasks/nsp-test/task.yml
  - task: snyk-test
    file: ci/concourse-ci/tasks/snyk-test/task.yml
  - task: npm-test
    file: ci/concourse-ci/tasks/npm-test/task.yml
  - task: yarn-test
    file: ci/concourse-ci/tasks/yarn-test/task.yml
    params:
      SNYK_TOKEN: {{snyk-token}}
      SNYK_USER_ID: {{snyk-user-id}}

- name: test-unboxit-tdd-es6-babel-jest
  plan:
  - get: ci
    trigger: true
  - get: source-code
    resource: unboxit-tdd-es6-babel-jest
    trigger: true
  - task: audit-test
    file: ci/concourse-ci/tasks/audit-test/task.yml
  - task: nsp-test
    file: ci/concourse-ci/tasks/nsp-test/task.yml
  - task: snyk-test
    file: ci/concourse-ci/tasks/snyk-test/task.yml
  - task: npm-test
    file: ci/concourse-ci/tasks/npm-test/task.yml
  - task: yarn-test
    file: ci/concourse-ci/tasks/yarn-test/task.yml
    params:
      SNYK_TOKEN: {{snyk-token}}
      SNYK_USER_ID: {{snyk-user-id}}

- name: test-unboxit-npm-scripts-only
  plan:
  - get: ci
    trigger: true
  - get: source-code
    resource: unboxit-npm-scripts-only
    trigger: true
  - task: audit-test
    file: ci/concourse-ci/tasks/audit-test/task.yml
  - task: nsp-test
    file: ci/concourse-ci/tasks/nsp-test/task.yml
  - task: snyk-test
    file: ci/concourse-ci/tasks/snyk-test/task.yml
    params:
      SNYK_TOKEN: {{snyk-token}}
      SNYK_USER_ID: {{snyk-user-id}}

- name: test-cloudbased-jeopardy
  plan:
  - get: ci
    trigger: true
  - get: source-code
    resource: cloudbased-jeopardy
    trigger: true
  - task: audit-test
    file: ci/concourse-ci/tasks/audit-test/task.yml
  - task: nsp-test
    file: ci/concourse-ci/tasks/nsp-test/task.yml
  - task: snyk-test
    file: ci/concourse-ci/tasks/snyk-test/task.yml
    params:
      SNYK_TOKEN: {{snyk-token}}
      SNYK_USER_ID: {{snyk-user-id}}

resources:
- name: ci
  type: git
  source:
    uri: git@github.com:gdumitrescu/testing-ci.git
    branch: master
    private_key: {{private-key}}

- name: unboxit-sequelgen
  type: git
  source:
    uri: git@github.com:unboxit/sequelgen.git
    branch: master
    private_key: {{private-key}}

- name: unboxit-nosequelgen
  type: git
  source:
    uri: git@github.com:unboxit/nosequelgen.git
    branch: master
    private_key: {{private-key}}

- name: unboxit-elming
  type: git
  source:
    uri: git@github.com:unboxit/elming.git
    branch: master
    private_key: {{private-key}}

- name: unboxit-tdd-es6-babel-jest
  type: git
  source:
    uri: git@github.com:unboxit/tdd-es6-babel-jest.git
    branch: master
    private_key: {{private-key}}

- name: unboxit-npm-scripts-only
  type: git
  source:
    uri: git@github.com:unboxit/npm-scripts-only.git
    branch: master
    private_key: {{private-key}}

- name: cloudbased-jeopardy
  type: git
  source:
    uri: git@github.com:cloudbased/jeopardy.git
    branch: master
    private_key: {{private-key}}
